streams:
    - https://online.hitfm.ua/HitFM_Best_HD
    - https://online.hitfm.ua/HitFM_Top_HD
    - https://cast.radiogroup.com.ua/nrj_hits320
    - https://online.kissfm.ua/KissFM_HD
    - https://cast.radiogroup.com.ua/terrace320
    - https://cast.radiogroup.com.ua/chillout320
current_stream: 1
current_volume: "1.00"
